services:
  php-kata:
    build: .
    container_name: rpg-php-kata
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public"]